### ISSUE TITLE
Security -> Research -> Viability of MFA for raw data submission

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/sheepdog#103]
-Viability of MFA 
-Ensure least privilege (only submit data to their folder)
-What can be logged or audited to find suspicious behavior
    -Failed data validation
    -Moving from folder to folder
    -Etc.
(For submission of data only, not console access or analyzing data)

**Comment by trevars** [comment]
Asked Rebecca, she said:
so i think we are ok with a one-time url that expires
i need to write it up as an exception i think, but we need to get the approval workflow going in lockpath
