### ISSUE TITLE
PXD-542 ⁃ _all and root submssions return 0 bytes

### ISSUE THREAD

**Issue by david4096** [uc-cdis/sheepdog#139]
When choosing JSON serialization for `_all` and `root` nodes a 0-byte response is made. Is this intended? It returns 200 but doesn't parse as JSON.

https://dcp.bionimbus.org/api/v0/submission//topmed/public/export?format=json&node_label=_all

https://github.com/david4096/sheepdog-exporter/issues/8

**Comment by philloooo** [comment]
it should return 400 with error message that makes more sense
