### ISSUE TITLE
export functionality for all data

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/sheepdog#18]
https://github.com/kids-first/kf-internal-tracker/issues/19
- modify `/export` endpoint to take no argument and return all nodes under the project
- benchmark existing `/export` endpoint
- see either adhoc query or cronjob of dump of manifest

**Comment by rudyardrichter** [comment]
What does "see either adhoc query or cronjob of dump of manifest" mean?

**Comment by zflamig** [comment]
We want to know if its fast enough that we can let users query the /export endpoint to dump all the data at arbitrary times or if its slow so that we need to limit it to say once a day (cronjob) where we would then just make a nightly dump available

**Comment by rudyardrichter** [comment]
Ah, good. Makes sense.

**Comment by allisonheath** [comment]
Wanted to check in on this - right now we have 18,560 samples for Kids First slated. Each of these sample nodes are going to have case, demographics, diagnosis and likely multiple files associated - starting to load data into the dev environment. For performance testing, currently we're targeting 100,000 samples, just in terms of the scale expected. 

cc @baileyckelly @fgerthoffert

**Comment by joneubank** [comment]
@philloooo Looking forward to this functionality. When complete, will we be able to limit the export such that the file will only contain one node type? ie. an export URL for all cases in a project, one for all samples, one for all... etc.

Right now we are operating with the model of one TSV file per node type, would like to know how the data will look if all nodes are exported together.

**Comment by rudyardrichter** [comment]
@joneubank Yes, that's what the related PR does (#41), so for example
```
/program/project/export?node_label=case
```
will return a TSV of all the nodes with type `'case'`.
