### ISSUE TITLE
allow registering URLs for file type node's submission

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/sheepdog#64]
Sheepdog needs to take a URL and pass it through to Indexd

**Comment by Avantol13** [comment]
spent ~2 hours on this

**Comment by Avantol13** [comment]
spent another ~1 hr fixing up after review

**Comment by Avantol13** [comment]
spent another ~5 hours refactoring and integration testing

**Comment by Avantol13** [comment]
spent another ~2 hours on this today to get it all fixed up and merged
