### ISSUE TITLE
downloaded TSVs have "id" column twice 

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/sheepdog#84]
When using API to download submitted TSVs, for instance:

https://data.bloodpac.org/api/v0/submission/internal/test/export?format=tsv&ids=66341f7f-7a32-4943-bcaa-5ac95f2849ee

the resulting tsv file includes the column "id" duplicated.

**Comment by zflamig** [comment]
https://github.com/uc-cdis/sheepdog/blob/8b715de5327723655f6c06206b88b3a7a991bd82/sheepdog/utils/transforms/graph_to_doc.py#L690 should just be exclude_id=True?

**Comment by thanh-nguyen-dang** [comment]
spent 1 hours to find the bug, implement, test, and refactoring code
but, spent 4 hours to reconfigure the local setting that was changed after migrating to the new laptop and dependency libraries broken
